### ISSUE TITLE
listItem 为两列或者三列怎么设置呢?

### ISSUE THREAD

**Issue by phpsmarter** [Rahim-Chan/taro-listview#1]
listItem 为两列或者三列怎么设置呢?

**Comment by Rahim-Chan** [comment]
@phpsmarter 是指tab下的多个list切换吗

**Comment by yushaogg** [comment]
您好,组件文档可以完善下嘛? 代码引入后报错~~ 请教下您,这个;里面的数据是请求下来设置给state中的吗?  还是可以自己定义测试数据 看看样子?

**Comment by Rahim-Chan** [comment]
> 您好,组件文档可以完善下嘛? 代码引入后报错~~ 请教下您,这个;里面的数据是请求下来设置给state中的吗? 还是可以自己定义测试数据 看看样子?

获取数据那个时伪代码，需要自己去模拟，或者真是的异步请求。

**Comment by yushaogg** [comment]
大佬能否贴下完整的代码呀~ 哈哈

**Comment by Rahim-Chan** [comment]
> 大佬能否贴下完整的代码呀~ 哈哈

[项目代码](https://github.com/Rahim-Chan/taro-listview/tree/master/src/pages)
可直接启动

**Comment by mataoct** [comment]
同问，如果要展示两列或者三列数据 如何配置，react-native 的List 有个属性是 number of columns 

就是
A|B
C|D
E|F
这种布局

**Comment by Rahim-Chan** [comment]
> 同问，如果要展示两列或者三列数据 如何配置，react-native 的List 有个属性是 number of columns
> 
> 就是
> A|B
> C|D
> E|F
> 这种布局

两、三列应该只是样式上的控制而已吧；
