### ISSUE TITLE
onScrollToLower方法无法被触发

### ISSUE THREAD

**Issue by JuniorFirster** [Rahim-Chan/taro-listview#12]
上拉加载代码无法被触发，代码如下
onScrollToLower = (fn) => {
    console.log('到底了');
   fn()
 };
........
<ListView
        hasMore={hasMore}
        onScrollToLower={(fn) => {this.onScrollToLower(fn)}}
      >
......
</ListView>

**Comment by Rahim-Chan** [comment]
> 上拉加载代码无法被触发，代码如下
> onScrollToLower = (fn) => {
> console.log('到底了');
> fn()
> };
> ........
> <ListView
> hasMore={hasMore}
> onScrollToLower={(fn) => {this.onScrollToLower(fn)}}
> >
> ......

没有固定高度
