### ISSUE TITLE
请问该长列表组件是无限滚动组件吗

### ISSUE THREAD

**Issue by AwesomeDevin** [Rahim-Chan/taro-listview#13]

**Comment by Rahim-Chan** [comment]
你说的是上拉获取更多嘛，如果是的话就是无限滚动。

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Devin <notifications@github.com>
发送时间: 星期二, 十二月 10, 2019 8:40 下午
收件人: Rahim-Chan/taro-listview
抄送: Subscribed
主题: [Rahim-Chan/taro-listview] 请问该长列表组件是无限滚动组件吗 (#13)


―

**Comment by Rahim-Chan** [comment]
> _No description provided._

你有啥想法吗

**Comment by 364734461** [comment]
有做列表的装载和卸载吗？

**Comment by Rahim-Chan** [comment]
> 有做列表的装载和卸载吗？

能具体举个例子吗

**Comment by 364734461** [comment]
这里指的是长列表的性能优化。例如：RN的 FlatList

**Comment by Rahim-Chan** [comment]
> 这里指的是长列表的性能优化。例如：RN的 FlatList

有的正在施工中，在virtul分支中。目前已经完成列表的diff但是体验有待提升。属于WIP状态。

**Comment by Norbert-Nayman** [comment]
> > 这里指的是长列表的性能优化。例如：RN的 FlatList
> 
> 有的正在施工中，在virtul分支中。目前已经完成列表的diff但是体验有待提升。属于WIP状态。

刚才得知微信小程序有页面节点限制，公司新项目首页用了 6 个taro-listview用于展示商品列表，很慌。请问有recycle-view的机制吗？

**Comment by Rahim-Chan** [comment]
> > > 这里指的是长列表的性能优化。例如：RN的 FlatList
> > 
> > 
> > 有的正在施工中，在virtul分支中。目前已经完成列表的diff但是体验有待提升。属于WIP状态。
> 
> 刚才得知微信小程序有页面节点限制，公司新项目首页用了 6 个taro-listview用于展示商品列表，很慌。请问有recycle-view的机制吗？

在借鉴他的源码中，核心的列表优化已经好了，但是优化还有问题，业务缠身；推动有点慢
