### ISSUE TITLE
能支持配置一下，不要下拉刷新吗，因为太卡顿

### ISSUE THREAD

**Issue by 364734461** [Rahim-Chan/taro-listview#15]

**Comment by Rahim-Chan** [comment]
> _No description provided._

能说一下卡顿是在什么环境和机型吗？
onPullDownRefresh这个这个props就不会触发下拉的动作。

**Comment by 364734461** [comment]
不设置onPullDownRefresh   会出现问题，看了一下源码，应该没有开放这个功能吧？有例子吗

下拉卡顿是在   小程序     ipx   2018年初版的

**Comment by Rahim-Chan** [comment]
> 不设置onPullDownRefresh 会出现问题，看了一下源码，应该没有开放这个功能吧？有例子吗
> 
> 下拉卡顿是在 小程序 ipx 2018年初版的

![image](https://user-images.githubusercontent.com/18487314/71303070-d4f16580-23ee-11ea-99f1-477ebb38bbaa.png)
```
<ListView
            lazy
            ref={node => this.insRef(node)}
            isLoaded={isLoaded}
            isError={error}
            hasMore={hasMore}
            style={{height: '100vh'}}
            isEmpty={isEmpty}
            // onPullDownRefresh={fn => this.pullDownRefresh(fn)}
            onScrollToLower={this.onScrollToLower}
          >
```

**Comment by 364734461** [comment]
`
fetchInit = () => {
    const {onPullDownRefresh} = this.props;
    this.resetLoad(1);
    if (onPullDownRefresh) {
      onPullDownRefresh(() => {
        this.setState({isInit: true});
        this.resetLoad(0, () =>{
          this.setState({isInit: false});
        });
      });
    }
  };
`
这段代码中，如果没有 onPullDownRefresh 将，无法执行resetLoad（0），resetLoad 中调用了 moveBox    ，当不为 0 的时候，会锁定滚动。
demo中有写手动触发 fetchInit 方法，但是我现在还没有看为什么，用意是什么

可以发一个没有下拉的完整的示例吗？

**Comment by 364734461** [comment]
needInit   关闭后，是否有什么副作用

**Comment by Rahim-Chan** [comment]
fetchInit的用意是为了，控制下拉动画出现+加载onPullDownRefresh的数据。

needInit关闭后不会出现任何副作用，是一个可选线。自动触发fetchInit方法。

````
componentDidMount() {
    this.pullDownRefresh()
  }

  pullDownRefresh = async (rest?) => {
    pageIndex = 1;
    const res = await this.getData(1);
    this.setState(res);
    if (rest) rest()
  };

<ListView
  hasMore={hasMore}
  style={{height: '100vh'}}
  onScrollToLower={this.onScrollToLower}
 >
 {列表内容}
</ListView>
```
这给是部分代码。具有上拉加载更多没有下拉的例子

**Comment by Norbert-Nayman** [comment]
> > _No description provided._
> 
> 能说一下卡顿是在什么环境和机型吗？
> onPullDownRefresh这个这个props就不会触发下拉的动作。

安卓机型下拉会卡顿 iOS没问题

**Comment by Rahim-Chan** [comment]
> > > _No description provided._
> > 
> > 
> > 能说一下卡顿是在什么环境和机型吗？
> > onPullDownRefresh这个这个props就不会触发下拉的动作。
> 
> 安卓机型下拉会卡顿 iOS没问题

安卓的小程序卡顿，从跟不上解决不了
[小程序卡顿](https://github.com/Rahim-Chan/taro-listview/issues/8)
