### ISSUE TITLE
请问，可否不绑定cli 1.3.5？

### ISSUE THREAD

**Issue by oxygen-xx** [Rahim-Chan/taro-listview#16]
在Taro现有机制下，插件绑定cli,会引起整个的项目都绑定cli
我们的list可否不绑定"@tarojs/cli": "1.3.15",？

**Comment by oxygen-xx** [comment]
改为peerDev的方式设置cli

**Comment by Rahim-Chan** [comment]
> 改为peerDev的方式设置cli

好的感谢你的issue，我去验证一下

**Comment by Rahim-Chan** [comment]
> 改为peerDev的方式设置cli

您好
- 我理解是不依赖cli；
- 而peer会把依赖放到node_modules文件夹的目录第一层；eg：node_modules/@taro-cli；
- 我现在把他改成dev依赖关系，在安装库的时候不会引入这个库`@taro-cli`；
希望这个改动符合您的要求
