### ISSUE TITLE
下拉刷新安卓机卡顿

### ISSUE THREAD

**Issue by Norbert-Nayman** [Rahim-Chan/taro-listview#18]
请参考[taro-list](https://github.com/raohong/taro-list)

基于 ScrollView 在安卓机上下拉刷新非常顺滑

**Comment by Rahim-Chan** [comment]
> 请参考[taro-list](https://github.com/raohong/taro-list)
> 
> 基于 ScrollView 在安卓机上下拉刷新非常顺滑

好的感谢

**Comment by Rahim-Chan** [comment]
> 请参考[taro-list](https://github.com/raohong/taro-list)
> 
> 基于 ScrollView 在安卓机上下拉刷新非常顺滑

联系方式有吗交流一波

**Comment by Rahim-Chan** [comment]
已修复

**Comment by Norbert-Nayman** [comment]
> > 请参考[taro-list](https://github.com/raohong/taro-list)
> > 基于 ScrollView 在安卓机上下拉刷新非常顺滑
> 
> 联系方式有吗交流一波

vx:RabbitFetters
