### ISSUE TITLE
滑动的时候报错：TypeError: _taroWeapp2.default[key] is not a function

### ISSUE THREAD

**Issue by xiaomei991** [Rahim-Chan/taro-listview#19]
thirdScriptError
_taroWeapp2.default[key] is not a function;at SelectorQuery callback function
TypeError: _taroWeapp2.default[key] is not a function

**Comment by Rahim-Chan** [comment]
> thirdScriptError
> _taroWeapp2.default[key] is not a function;at SelectorQuery callback function
> TypeError: _taroWeapp2.default[key] is not a function

请发一下listview开启的配置，是在小程序环境下吗

**Comment by woaixiaojuan** [comment]
同样的问题，求助

**Comment by Rahim-Chan** [comment]
> 同样的问题，求助
请发一下listview开启的配置！

必然复现吗？
怎么复现？
是在小程序环境下吗
是在什么方向滑动产生的

**Comment by Rahim-Chan** [comment]
> 同样的问题，求助
请发一下listview开启的配置！

必然复现吗？
怎么复现？
是在小程序环境下吗
是在什么方向滑动产生的

**Comment by woaixiaojuan** [comment]
`<ListView
                style={{ height: '100vh' }}
                isEmpty={false}
                lazy
                distanceToRefresh={40}
                ref={node => this.insRef(node)}
                onPullDownRefresh={fn => this.pullDownRefresh(fn)}
                onScrollToLower={fn => this.onScrollToLower(fn)}
            >
   {this.props.children}
            </ListView>
`

**Comment by Rahim-Chan** [comment]
x

> `<ListView style={{ height: '100vh' }} isEmpty={false} lazy distanceToRefresh={40} ref={node => this.insRef(node)} onPullDownRefresh={fn => this.pullDownRefresh(fn)} onScrollToLower={fn => this.onScrollToLower(fn)} > {this.props.children} </ListView> `

先把lazy去掉，我排除一下问题，是在小程序环境吗

**Comment by woaixiaojuan** [comment]
> x
> 
> > `<ListView style={{ height: '100vh' }} isEmpty={false} lazy distanceToRefresh={40} ref={node => this.insRef(node)} onPullDownRefresh={fn => this.pullDownRefresh(fn)} onScrollToLower={fn => this.onScrollToLower(fn)} > {this.props.children} </ListView> `
> 
> 先把lazy去掉，我排除一下问题，是在小程序环境吗

微信小程序开发者工具调试报错

**Comment by woaixiaojuan** [comment]
> lazy

lazy去掉没有报错，另外用你给的例子也不会报错，不知道是不是我这配置有问题？
另外，可以请教下您，我可以自定义下拉加载动画吗(比如放一直gif图片)？

**Comment by Rahim-Chan** [comment]
- 报错问题我在排查
- 自定义加载动画的画，我晚点新增一个props类型

**Comment by woaixiaojuan** [comment]
> * 报错问题我在排查
> * 自定义加载动画的画，我晚点新增一个props类型

感谢

**Comment by Rahim-Chan** [comment]
> > * 报错问题我在排查
> > * 自定义加载动画的画，我晚点新增一个props类型
> 
> 感谢

- 报错问题解决了
- 新增renderCustomizeLoading，customizeLoading字段；
customizeLoading是确定是否开启自定义；
renderCustomizeLoading是放自定义的内容

**Comment by woaixiaojuan** [comment]
> > > * 报错问题我在排查
> > > * 自定义加载动画的画，我晚点新增一个props类型
> > 
> > 
> > 感谢
> 
> * 报错问题解决了
> * 新增renderCustomizeLoading，customizeLoading字段；
>   customizeLoading是确定是否开启自定义；
>   renderCustomizeLoading是放自定义的内容

感谢，
customizeLoading={true}
                renderCustomizeLoading={
                    <Image  src={‘***'}></Image>
                }
是这样子书写吗?

**Comment by Rahim-Chan** [comment]
> > > > * 报错问题我在排查
> > > > * 自定义加载动画的画，我晚点新增一个props类型
> > > 
> > > 
> > > 感谢
> > 
> > 
> > 
> > * 报错问题解决了
> > * 新增renderCustomizeLoading，customizeLoading字段；
> >   customizeLoading是确定是否开启自定义；
> >   renderCustomizeLoading是放自定义的内容
> 
> 感谢，
> customizeLoading={true}
> renderCustomizeLoading={
> <Image src={‘***'}>
> }
> 是这样子书写吗?
是的
customizeLoading可以简写

**Comment by woaixiaojuan** [comment]
> > 感谢，
> > customizeLoading={true}
> > renderCustomizeLoading={
> > <Image src={‘***'}>
> > }
> > 是这样子书写吗?
> > 是的
> > customizeLoading可以简写

我这样写了，没有显示出来，是我哪儿写错了吗？
自定义页面UI的属性是怎么书写呢？
比如:
color=‘#ff0000'
indicator release = {'加载中'}
是这样吗？

**Comment by Rahim-Chan** [comment]
> > > 感谢，
> > > customizeLoading={true}
> > > renderCustomizeLoading={
> > > <Image src={‘***'}>
> > > }
> > > 是这样子书写吗?
> > > 是的
> > > customizeLoading可以简写
> 
> 我这样写了，没有显示出来，是我哪儿写错了吗？
> 自定义页面UI的属性是怎么书写呢？
> 比如:
> color=‘#ff0000'
> indicator release = {'加载中'}
> 是这样吗？
```
<ListView
        renderCustomizeLoading={(<View>自定义</View>)}
        customizeLoading
          >          
```
这样写是在下拉触发加载等时候，替换oading的等待动画；

至于下拉过程的效果只能替换文字
