### ISSUE TITLE
页面元素在， 但是显示空白，isEmpty为false

### ISSUE THREAD

**Issue by GitManr** [Rahim-Chan/taro-listview#20]
![image](https://user-images.githubusercontent.com/25880083/76685786-5143bf80-6651-11ea-9f81-81b390843833.png)

 class Home extends Component {
  constructor(){
    super(...arguments)
    this.state = {
      isLoaded: false,
      error: false,
      hasMore: true,
      isEmpty: false,
    }
  }
  componentWillMount () { }

  componentDidMount () { 
  this.refList.fetchInit()
  }

  pullDownRefresh = async (rest) => {
    console.log('rest: ', rest);
    // pageIndex = 1;
    // const res = await this.getData(1);
    // this.setState(res);
    rest()
  };

  onScrollToLower = async (fn) => {
    console.log('onScrollToLower: ');
    
    fn();
  };
  render () {
    const { isLoaded, hasMore, error, isEmpty } = this.state;
    return (
      <View className='home'>
        <ListView
          lazy
          ref={node => this.refList = node}
          isLoaded={ isLoaded }
          isError={error}
          hasMore={hasMore}
          style={{ height: '100vh' }}
          isEmpty={isEmpty}
          onPullDownRefresh={fn => this.pullDownRefresh(fn)}
          onScrollToLower={this.onScrollToLower}
        >
        ......此处省略业务代码
        </ListView>

      </View>
    )
  }
}

**Comment by Rahim-Chan** [comment]
isLoaded的设置为true

**Comment by GitManr** [comment]
> isLoaded的设置为true

可以了， 非常感谢
