### ISSUE TITLE
yarn add 安装，react native 打开报错了

### ISSUE THREAD

**Issue by PangYiMing** [Rahim-Chan/taro-listview#21]
error: bundling failed: Error: Unable to resolve module `./index.scss` from `/Users/edz/workspace/taroRnAppLearn/node_modules/taro-listview/dist/weapp/components/list-view/index.tsx`:

**Comment by Rahim-Chan** [comment]
> error: bundling failed: Error: Unable to resolve module `./index.scss` from `/Users/edz/workspace/taroRnAppLearn/node_modules/taro-listview/dist/weapp/components/list-view/index.tsx`:

本项目对原始App没有兼容
