### ISSUE TITLE
建议block.tsx 中 设置缓存 lazyBox 改为参数

### ISSUE THREAD

**Issue by Smi1e96** [Rahim-Chan/taro-listview#23]
# 缓存变量 lazyBox 改为参数
当 开发版、体验版、正式版 都在运行时 都在使用这一个缓存 容易出现混乱:smile:

这样的话 微信可以使用 <code>wx.getAccountInfoSync()</code>来设置不同版本中 缓存 

> tips: 我也可以拉个pr 合并下:stuck_out_tongue_closed_eyes:

**Comment by Rahim-Chan** [comment]
> # 缓存变量 lazyBox 改为参数
> 当 开发版、体验版、正式版 都在运行时 都在使用这一个缓存 容易出现混乱😄
> 
> 这样的话 微信可以使用 `wx.getAccountInfoSync()`来设置不同版本中 缓存
> 
> > tips: 我也可以拉个pr 合并下😝

可以的！请提个PR。
