### ISSUE TITLE
这个 isLoaded 属性是用来干啥的？一直没有搞明白

### ISSUE THREAD

**Issue by Desgard** [Rahim-Chan/taro-listview#24]
文档中也没有出现。我这边只要传入这个变量，列表就会变空白。

**Comment by Rahim-Chan** [comment]
这个是用来控制骨架屏的、判断是不是首次渲染；是的话未开启骨架屏；
[image: image.png]

Gua <notifications@github.com> 于2020年4月18日周六 上午11:06写道：

**Comment by Rahim-Chan** [comment]
> 文档中也没有出现。我这边只要传入这个变量，列表就会变空白。

文档里面有该属性
