### ISSUE TITLE
onScrollToLower loading 并没有显示，滚动的区域高度写固定值，不能随父元素的高而定

### ISSUE THREAD

**Issue by whq920729** [Rahim-Chan/taro-listview#25]
滚动的区域高度写固定值，不能随父元素的高而定，onScrollToLower loading 并没有显示
style={{height: '100vh'}} 
大多数使用场景，这个高度都是随父元素的高度而定的，但是现在必须要给一个固定值，导致使用其他方法给这个滚动区域赋值高度，能否改进？

**Comment by Rahim-Chan** [comment]
> 滚动的区域高度写固定值，不能随父元素的高而定，onScrollToLower loading 并没有显示
> style={{height: '100vh'}}
> 大多数使用场景，这个高度都是随父元素的高度而定的，但是现在必须要给一个固定值，导致使用其他方法给这个滚动区域赋值高度，能否改进？

多谢宝贵建议，已添加```autoHeight```属性开起即可
