### ISSUE TITLE
new feature : 能否添加监听 scrolling 事件，除了触顶和触底，同时也需要实时监听滚动的位置

### ISSUE THREAD

**Issue by whq920729** [Rahim-Chan/taro-listview#26]
需求是，滚动区域内部有“吸顶”导航，我是在滚动区域外部放置了另外一个导航，当滚动区域内部的导航超出屏幕，外部的导航显示，现在无法判断滚动的位置，请大佬给点建议，谢谢！

**Comment by Rahim-Chan** [comment]
> 需求是，滚动区域内部有“吸顶”导航，我是在滚动区域外部放置了另外一个导航，当滚动区域内部的导航超出屏幕，外部的导航显示，现在无法判断滚动的位置，请大佬给点建议，谢谢！

组件有暴露onScroll的方法

**Comment by whq920729** [comment]
> > 需求是，滚动区域内部有“吸顶”导航，我是在滚动区域外部放置了另外一个导航，当滚动区域内部的导航超出屏幕，外部的导航显示，现在无法判断滚动的位置，请大佬给点建议，谢谢！
> 
> 组件有暴露onScroll的方法
`onScroll = (e) => {
    console.log(e)
  }`

**Comment by whq920729** [comment]
谢谢，更新版本，能正常使用了！

**Comment by whq920729** [comment]
> > 需求是，滚动区域内部有“吸顶”导航，我是在滚动区域外部放置了另外一个导航，当滚动区域内部的导航超出屏幕，外部的导航显示，现在无法判断滚动的位置，请大佬给点建议，谢谢！
> 
> 组件有暴露onScroll的方法

暴露的onScroll方法，在 H5 平台上可以正常捕获 event.detail ，weapp 平台不能捕获当前 event，请大佬指点一下

**Comment by Rahim-Chan** [comment]
那只能通过小程序的元素选择器、在滚动的时候、实时获取要吸顶的元素的高度然后做判断

**Comment by Rahim-Chan** [comment]
那只能通过小程序的元素选择器、在滚动的时候、实时获取要吸顶的元素的高度然后做判断

> > > 需求是，滚动区域内部有“吸顶”导航，我是在滚动区域外部放置了另外一个导航，当滚动区域内部的导航超出屏幕，外部的导航显示，现在无法判断滚动的位置，请大佬给点建议，谢谢！
> > 
> > 
> > 组件有暴露onScroll的方法
> 
> 暴露的onScroll方法，在 H5 平台上可以正常捕获 event.detail ，weapp 平台不能捕获当前 event，请大佬指点一下

那只能通过小程序的元素选择器、在滚动的时候、实时获取要吸顶的元素的高度然后做判断
