### ISSUE TITLE
小程序骨架屏在苹果手机上无效

### ISSUE THREAD

**Issue by Jack-cup** [Rahim-Chan/taro-listview#27]
小程序骨架屏在苹果手机上无效

**Comment by Rahim-Chan** [comment]
> 小程序骨架屏在苹果手机上无效

H5还是小程序、调试工具可以吗？配置参数贴一下

**Comment by Jack-cup** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rahim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 下午4:21
收件人:&nbsp;"Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;;
抄送:&nbsp;"王辉"<1027332684@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Rahim-Chan/taro-listview] 小程序骨架屏在苹果手机上无效 (#27)





  
小程序骨架屏在苹果手机上无效
  
H5还是小程序、调试工具可以吗？配置参数贴一下
