### ISSUE TITLE
多页面使用listview，第二个页面下拉刷新没有动画效果

### ISSUE THREAD

**Issue by tangtao13** [Rahim-Chan/taro-listview#36]
一个手机端项目，使用大大的组件，封装成一个公共的组件，在消息tab页，待办tab页引用它，，如果先进入消息tab页，下拉刷新可以正常显示，然后进入待办tab页，下拉刷新没有动画。

**Comment by tangtao13** [comment]
`调试发现，下拉刷新操作操作DOM：`this.updateDampText(needPullDown); this.moveBox(height);` 这两个函数，选择的DOM是先加载的DOM

**Comment by tangtao13** [comment]
能多传一个props 属性，用来操作` const target = document.getElementById("tip-dampText");`和 `const target = document.getElementById("bodyView");` 这两个ID选择器么？可以将tip-dampText和bodyView变成动态的么？

**Comment by Rahim-Chan** [comment]
> 一个手机端项目，使用大大的组件，封装成一个公共的组件，在消息tab页，待办tab页引用它，，如果先进入消息tab页，下拉刷新可以正常显示，然后进入待办tab页，下拉刷新没有动画。

这里`然后进入待办tab页，下拉刷新没有动画。`是指再次进入页面吗？

**Comment by Rahim-Chan** [comment]
> `调试发现，下拉刷新操作操作DOM：`this.updateDampText(needPullDown); this.moveBox(height);` 这两个函数，选择的DOM是先加载的DOM

您的意思是页面上有两个`#tip-dampText`是吗，在多个组件同时挂载的时候。

**Comment by Rahim-Chan** [comment]
> 能多传一个props 属性，用来操作` const target = document.getElementById("tip-dampText");`和 `const target = document.getElementById("bodyView");` 这两个ID选择器么？可以将tip-dampText和bodyView变成动态的么？

是不是，我把第二个问题解决了，就不需要这个功能了；
还是说这个功能你有啥用处，如果在H5模式下是可以通过DOM来直接操控。

**Comment by tangtao13** [comment]
项目也是使用Taro开发的。在H5模式下，在加载多个listview后，项目中存在多个#tip-dampText和#bodyview,下拉刷新的时候，会操作第一个选择到的DOM，无法操作想操作的DOM.能传递一个props，用来使#tip-dampText和#bodyview这两个DOM保持唯一么？

**Comment by Rahim-Chan** [comment]
> 项目也是使用Taro开发的。在H5模式下，在加载多个listview后，项目中存在多个#tip-dampText和#bodyview,下拉刷新的时候，会操作第一个选择到的DOM，无法操作想操作的DOM.能传递一个props，用来使#tip-dampText和#bodyview这两个DOM保持唯一么？

我修复一下
