### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by wangweifeng66** [Rahim-Chan/taro-listview#37]
直接引用编译报错：
![1589868492800](https://user-images.githubusercontent.com/26533125/82290757-36d3ec80-99da-11ea-92f3-30139cdb72e2.jpg)

Taro CLI 3.0.0-beta.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5 
      eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.13.1 => 16.13.1

**Comment by Rahim-Chan** [comment]
> 直接引用编译报错：
> ![1589868492800](https://user-images.githubusercontent.com/26533125/82290757-36d3ec80-99da-11ea-92f3-30139cdb72e2.jpg)
> 
> Taro CLI 3.0.0-beta.5 environment info:
> System:
> OS: macOS 10.14.6
> Shell: 5.3 - /bin/zsh
> Binaries:
> Node: 11.10.1 - /usr/local/bin/node
> Yarn: 1.22.4 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> npmPackages:
> @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5
> @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5
> @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5
> eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5
> nervjs: ^1.5.6 => 1.5.6
> react: ^16.13.1 => 16.13.1

hi，我这边无法复现；
请附上`依赖配置`和`事例例代码`

**Comment by wangweifeng66** [comment]
这个是我用taro init 新建的项目，引入了taro-listview 编辑后还出现这个错误
地址：https://github.com/summer88123/errorDemo.git
麻烦看一下

**Comment by Rahim-Chan** [comment]
> 这个是我用taro init 新建的项目，引入了taro-listview 编辑后还出现这个错误
> 地址：https://github.com/summer88123/errorDemo.git
> 麻烦看一下

发现是taro3.0 beta版本编译的问题，这版本还不稳定，建议降级到2.x版本
