### ISSUE TITLE
h5 语法报错

### ISSUE THREAD

**Issue by liganghui** [Rahim-Chan/taro-listview#38]
taro 版本 v2.2.9
taro-listview 版本  v1.4.2

使用插件示例编译成h5浏览器报错 , 如图.
![微信截图_20200708163114](https://user-images.githubusercontent.com/15844198/86896746-06d2db00-c139-11ea-92bd-06180fc245b1.png)
![微信截图_20200708163128](https://user-images.githubusercontent.com/15844198/86896756-0a666200-c139-11ea-895f-b17ab25ff69c.png)

**Comment by Rahim-Chan** [comment]
没有看到同款报错。
还是加了个默认参数。
