### ISSUE TITLE
taro 3.0.2版本下 使用会报错

### ISSUE THREAD

**Issue by datafu** [Rahim-Chan/taro-listview#39]
ncaught (in promise) TypeError: Super expression must either be null or a function
    at _inherits (inherits.js?66c3:4)
    at eval (index.js?2feb:5)
    at eval (index.js?2feb:5)
    at Module../node_modules/_taro-listview@1.4.3@taro-listview/dist/h5/components/skeleton/index.js (44.js:242)
    at __webpack_require__ (app.js:64)
    at eval (index.js:15)
    at Module../node_modules/_taro-listview@1.4.3@taro-listview/dist/h5/components/list-view/index.js (44.js:137)
    at __webpack_require__ (app.js:64)
    at eval (index.js?5d25:1)
    at Module../node_modules/_taro-listview@1.4.3@taro-listview/dist/h5/index.js (44.js:265)

**Comment by mitayou** [comment]
应该是还不兼容3.x的版本吧

**Comment by jschyz** [comment]
同问

**Comment by Rahim-Chan** [comment]
是的还没有支持3的版本，一周内升级；不知道该组件的版本占有率多少;

**Comment by mitayou** [comment]
> 是的还没有支持3的版本，一周内升级；不知道该组件的版本占有率多少;

现在文档都是优先升级3.x，在实际开发中一般这种虚拟滚动固定高度是通过js来动态计算剩余屏幕高度来设置滚动条高度的吗？

**Comment by Rahim-Chan** [comment]
> > 是的还没有支持3的版本，一周内升级；不知道该组件的版本占有率多少;
> 
> 现在文档都是优先升级3.x，在实际开发中一般这种虚拟滚动固定高度是通过js来动态计算剩余屏幕高度来设置滚动条高度的吗？

不是很懂你想问的问题是什么？
虚拟滚动是什么操作？

**Comment by mitayou** [comment]
> 是的还没有支持3的版本，一周内升级；不知道该组件的版本占有率多少;
> 
> 现在文档都是优先升级3.x，在实际开发中一般这种虚拟滚动固定高度是通过js来动态计算剩余屏幕高度来设置滚动条高度的吗？
> 
> 不是很懂你想问的问题是什么？
> 虚拟滚动是什么操作？

我想表达的意思是虚拟列表，虚拟列表一般要设置整个容器的高度，想知道高度的计算方式

**Comment by Rahim-Chan** [comment]
> > 是的还没有支持3的版本，一周内升级；不知道该组件的版本占有率多少;
> > 现在文档都是优先升级3.x，在实际开发中一般这种虚拟滚动固定高度是通过js来动态计算剩余屏幕高度来设置滚动条高度的吗？
> > 不是很懂你想问的问题是什么？
> > 虚拟滚动是什么操作？
> 
> 我想表达的意思是虚拟列表，虚拟列表一般要设置整个容器的高度，想知道高度的计算方式

目前两种吧，小程序里面，用么全部固定高度，要么通过执行函数返回高度；
eg:
1. 100 * total
2. getHeight(n) * total

**Comment by MarsArbiter** [comment]
大佬,啥时候上新.  另外 demo 貌似起不来. 不知道你那边最近开过没有

**Comment by Rahim-Chan** [comment]
> 大佬,啥时候上新. 另外 demo 貌似起不来. 不知道你那边最近开过没有

V3.x.x的版本还没跑起来

**Comment by heartrainy** [comment]
确实跑3.x.x版本会报Super expression must either be null or a function的错误

**Comment by Rahim-Chan** [comment]
> 确实跑3.x.x版本会报Super expression must either be null or a function的错误

晚点发包，3.xx版本打包不一样了

**Comment by MarsArbiter** [comment]
> > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> 
> 晚点发包，3.xx版本打包不一样了

3.xx 的包估计什么时候出哦

**Comment by GreatAuk** [comment]
> > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> 
> 晚点发包，3.xx版本打包不一样了

厚脸皮的催个更😅

**Comment by TangPe** [comment]
> > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> 
> 晚点发包，3.xx版本打包不一样了

3.xx版本什么时候出

**Comment by Rahim-Chan** [comment]
> > > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> > 
> > 
> > 晚点发包，3.xx版本打包不一样了
> 
> 厚脸皮的催个更😅

打包遇上了问题今晚解决

**Comment by MarsArbiter** [comment]
给力啊老铁

**Comment by Rahim-Chan** [comment]
> > > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> > 
> > 
> > 晚点发包，3.xx版本打包不一样了
> 
> 3.xx版本什么时候出

出了记得踩坑

**Comment by Rahim-Chan** [comment]
> > > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> > 
> > 
> > 晚点发包，3.xx版本打包不一样了
> 
> 厚脸皮的催个更😅

可踩坑

**Comment by Rahim-Chan** [comment]
> > > 确实跑3.x.x版本会报Super expression must either be null or a function的错误
> > 
> > 
> > 晚点发包，3.xx版本打包不一样了
> 
> 3.xx 的包估计什么时候出哦

帮忙踩坑谢谢
