### ISSUE TITLE
Taro3.0.9中报错

### ISSUE THREAD

**Issue by SkyFitz** [Rahim-Chan/taro-listview#45]
taro 3.0.9
这是复现的demo地址  https://gitee.com/FlyReactNative/taro-listview-demo
<img width="774" alt="WX20200907-122137@2x" src="https://user-images.githubusercontent.com/48275320/92348202-f329fd80-f104-11ea-855f-d87b74681e23.png">

**Comment by Rahim-Chan** [comment]
是在RN里面的吗

**Comment by SkyFitz** [comment]
不是  是H5的

**Comment by SkyFitz** [comment]
上面有复现的demo地址，是个空项目，就一个页面引用的taro-listview。

**Comment by lostcixin** [comment]
你解决了吗

**Comment by Rahim-Chan** [comment]
> 你解决了吗

今日内解决

**Comment by Rahim-Chan** [comment]
> taro 3.0.9
> 这是复现的demo地址 https://gitee.com/FlyReactNative/taro-listview-demo
> <img alt="WX20200907-122137@2x" width="774" src="https://user-images.githubusercontent.com/48275320/92348202-f329fd80-f104-11ea-855f-d87b74681e23.png">

先吧lazy属性关闭，且LazyBlock标签替换掉

**Comment by Rahim-Chan** [comment]
暂时把npm里面的browser输出选项移除了;
- umd打包出来的产物有问题；Taro上挂在的api全部丢失；
