### ISSUE TITLE
taro3.0.15报错Super expression must either be null or a function

### ISSUE THREAD

**Issue by mrsquhuainan** [Rahim-Chan/taro-listview#49]

**Comment by liganghui** [comment]
+1

**Comment by liganghui** [comment]
且组件在Taro v3.0.15 未开启TS支持 微信小程序编译会报出 "‘Unexpected strict mode reserved word’" 错误 , 增加TS编译支持后 报 Super expression must either be null or a function

**Comment by liganghui** [comment]
> _没有提供描述。_

大概率原因是作者没有适配taro v3版本 , 临时解决方法 :
修改 node_modules/taro-listview/dist/weapp/components  各个组件的头部引用 .
将
````javascript
import Taro, {Component } from '@tarojs/taro';
````
修改为
````javascript
import Taro from '@tarojs/taro';
import React, { Component } from 'react'
````

**Comment by liganghui** [comment]
实测还有其他报错....... 弃坑

**Comment by liganghui** [comment]
研究了一下  找到原因了
微信小程序下 通过 默认导出的引用方式 编译会报错 列如:
````JavaScript
import  ListView  from 'taro-listview';
````
修改为
````JavaScript
import { ListView } from 'taro-listview';
````
如果 组件启用```lazy```属性 小程序编译也会报错 , 关闭即可初步正常运行

**Comment by Rahim-Chan** [comment]
> > _没有提供描述。_
> 
> 大概率原因是作者没有适配taro v3版本 , 临时解决方法 :
> 修改 node_modules/taro-listview/dist/weapp/components 各个组件的头部引用 .
> 将
> 
> ```js
> import Taro, {Component } from '@tarojs/taro';
> ```
> 
> 修改为
> 
> ```js
> import Taro from '@tarojs/taro';
> import React, { Component } from 'react'
> ```

在2.x.x版本已经做了taro3的升级了；

**Comment by liganghui** [comment]
> > > _没有提供描述。_
> > 
> > 
> > 大概率原因是作者没有适应taro v3版本，临时解决方法：
> > 修改node_modules / taro-listview / dist / weapp / components各个组件的标题引用。
> > 将
> > ```js
> > 进口 太郎， {元器件 } 从 '@ tarojs /芋头' ;
> > ```
> > 
> > 
> > 修改为
> > ```js
> >  从'@ tarojs / taro'导入Taro  ; 从'react'导入React ，{组件} 
> >       
> > ```
> 
> 在2.xx版本已经做了taro3的升级了；

...............大兄弟 你文档标明一下有2.x啊 ,  npm 安装还是1.x版本.....

**Comment by SkyFitz** [comment]
npm install -g taro-listview@2.0.3
没找到2.0.3版本
<img width="582" alt="WX20201103-212328@2x" src="https://user-images.githubusercontent.com/48275320/97990464-f1d23400-1e1a-11eb-97fa-c358c0b5de78.png">
