### ISSUE TITLE
2.0.3版本在 npm 包中找不到

### ISSUE THREAD

**Issue by Aliveing** [Rahim-Chan/taro-listview#52]
你好，我安装的时候在 [npm版本历史](https://www.npmjs.com/package/taro-listview?activeTab=versions) 中找不到 `2.0.3` 版本，但在 Github 的发版历史中可以找到，请问是不是 `git tag` 完忘记 `npm publish` 了。
虽然可以通过`yarn add https://github.com/Rahim-Chan/taro-listview.git` 安装主分支最新的，就是安装完没有编译出`dist目录`，并且无法用 `npm run build` 自行编译，看错误是 `package.json` 中缺少 `browser` 配置。

![image](https://user-images.githubusercontent.com/11768879/99190074-7b7cec80-279f-11eb-8db7-290c028bfb95.png)
![image](https://user-images.githubusercontent.com/11768879/99190077-7e77dd00-279f-11eb-9a19-06dc99831932.png)

**Comment by Rahim-Chan** [comment]
> 你好，我安装的时候在 [npm版本历史](https://www.npmjs.com/package/taro-listview?activeTab=versions) 中找不到 `2.0.3` 版本，但在 Github 的发版历史中可以找到，请问是不是 `git tag` 完忘记 `npm publish` 了。
> 虽然可以通过`yarn add https://github.com/Rahim-Chan/taro-listview.git` 安装主分支最新的，就是安装完没有编译出`dist目录`，并且无法用 `npm run build` 自行编译，看错误是 `package.json` 中缺少 `browser` 配置。
> 
> ![image](https://user-images.githubusercontent.com/11768879/99190074-7b7cec80-279f-11eb-8db7-290c028bfb95.png)
> ![image](https://user-images.githubusercontent.com/11768879/99190077-7e77dd00-279f-11eb-9a19-06dc99831932.png)

是的2.0.3版本有问题，被我删除了，请问这个版本是哪里来的默认按照的吗

**Comment by Aliveing** [comment]
我在 Github 的 [release](https://github.com/Rahim-Chan/taro-listview/releases) 中看到的 2.0.3 版本，主要是在 npm package 里找不到，所以想问一下是不是忘记发 npm 包了，既然 2.0.3 版本有问题的话那没事了，我把这个 issue 关掉。
还请劳烦有时间把这个版本先下掉，看见 release 中有新版就忍不住想升，升不上就心心念念😂。
![image](https://user-images.githubusercontent.com/11768879/99329602-8d52b280-28b9-11eb-94c5-59264e505007.png)

**Comment by Rahim-Chan** [comment]
> 我在 Github 的 [release](https://github.com/Rahim-Chan/taro-listview/releases) 中看到的 2.0.3 版本，主要是在 npm package 里找不到，所以想问一下是不是忘记发 npm 包了，既然 2.0.3 版本有问题的话那没事了，我把这个 issue 关掉。
> 还请劳烦有时间把这个版本先下掉，看见 release 中有新版就忍不住想升，升不上就心心念念😂。
> ![image](https://user-images.githubusercontent.com/11768879/99329602-8d52b280-28b9-11eb-94c5-59264e505007.png)

2.0.2在打包的时候出错了吗？什么环境

**Comment by Aliveing** [comment]
环境用的3.0.16，2.0.2在打包时没有问题，因为有个老工程用的 taro2.x，现在升 3.x 变动挺大，所以每个依赖包 check 一遍有没有新版本，其实就想问下 2.0.3 在 Github release 中能看到，并且写着 Bug Fixes，但是 npm 中找不到的原因。既然告知原因我就关掉了这个issue，下一步就会用 2.0.2 版本正式走测试流程，如果这个 issue 造成困扰十分抱歉。

**Comment by Rahim-Chan** [comment]
> 环境用的3.0.16，2.0.2在打包时没有问题，因为有个老工程用的 taro2.x，现在升 3.x 变动挺大，所以每个依赖包 check 一遍有没有新版本，其实就想问下 2.0.3 在 Github release 中能看到，并且写着 Bug Fixes，但是 npm 中找不到的原因。既然告知原因我就关掉了这个issue，下一步就会用 2.0.2 版本正式走测试流程，如果这个 issue 造成困扰十分抱歉。

Oh！Dear, 这没关系，我们需要你对问题抱有热忱对开发者；同时也感谢你的使用及反馈！
