### ISSUE TITLE
taro3.0.19使用taro-listview1.4.4版本报错

### ISSUE THREAD

**Issue by Leenf1214** [Rahim-Chan/taro-listview#54]
@Rahim-Chan 
![image](https://user-images.githubusercontent.com/29810970/99950012-e25d5f80-2db6-11eb-8142-8e396e2d0298.png)

**Comment by Rahim-Chan** [comment]
请用v2版本

**Comment by Leenf1214** [comment]
taro-listview2.0以上版本吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahim"<notifications@github.com&gt;; 
发送时间: 2020年11月23日(星期一) 晚上6:17
收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 
抄送: "Ⅴ"<1242600725@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Rahim-Chan/taro-listview] taro3.0.19使用taro-listview1.4.4版本报错 (#54)





 
请用v2版本

**Comment by Leenf1214** [comment]
谢谢
