### ISSUE TITLE
taro-listview2.0版本使用以下参数下拉刷新没有生效！

### ISSUE THREAD

**Issue by Leenf1214** [Rahim-Chan/taro-listview#55]
![image](https://user-images.githubusercontent.com/29810970/100381772-a9dab180-3054-11eb-8f46-1bbc957fc4db.png)

**Comment by Leenf1214** [comment]
@Rahim-Chan

**Comment by Leenf1214** [comment]
@Rahim-Chan

**Comment by Rahim-Chan** [comment]
> @Rahim-Chan 

waiting for ne

**Comment by Leenf1214** [comment]
ok

**Comment by Rahim-Chan** [comment]
@Leenf1214 H5跟小程序试过没问题呀，你的无法起作用嘛

**Comment by Leenf1214** [comment]
是的，之前我发了截图，参数都用了没有生效



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahim"<notifications@github.com&gt;; 
发送时间: 2020年11月29日(星期天) 下午2:47
收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 
抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55)





 
@Leenf1214 H5跟小程序试过没问题呀，你的无法起作用嘛

**Comment by Leenf1214** [comment]
taro版本：3.0.14&nbsp; taro-listview:2.0.2 设置下拉loading没有显示



 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahim"<notifications@github.com&gt;; 
发送时间: 2020年11月29日(星期天) 下午2:47
收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 
抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55)





 
@Leenf1214 H5跟小程序试过没问题呀，你的无法起作用嘛

**Comment by Rahim-Chan** [comment]
> taro版本：3.0.14&nbsp; taro-listview:2.0.2 设置下拉loading没有显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Rahim"<notifications@github.com&gt;; 发送时间: 2020年11月29日(星期天) 下午2:47 收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55) @Leenf1214 H5跟小程序试过没问题呀，你的无法起作用嘛 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

[有的呀，方便吧demo贴一个线上](https://codesandbox.io)
![image](https://user-images.githubusercontent.com/18487314/100561391-c6484980-32f3-11eb-83f6-4f7d34fed8a3.png)

**Comment by Leenf1214** [comment]
我发到git上面&nbsp;https://gitee.com/zo18/weapp-list



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahim"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 上午10:08
收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 
抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55)






taro版本：3.0.14&nbsp;&nbsp;taro-listview:2.0.2&nbsp;设置下拉loading没有显示
…
------------------&nbsp;原始邮件&nbsp;------------------&nbsp;发件人:&nbsp;"Rahim"<notifications@github.com&gt;;&nbsp;发送时间:&nbsp;2020年11月29日(星期天)&nbsp;下午2:47&nbsp;收件人:&nbsp;"Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;;抄送:&nbsp;“V”<1242600725@qq.com》；“提到”《mention@noreply.github.com&gt;;主题:关于：[Rahim-Chan/taro-listview]目标列表视图2。0版本使用以下参数下拉刷新没有生效！&nbsp;(#55)@Leenf1214H5跟小程序试过没问题呀，你的无法起作用嘛—你收到这个是因为你被提到了。直接回复此电子邮件，在GitHub上查看，或取消订阅.

有的呀,方便吧演示贴一个线上


—
你收到这个是因为你被提到了。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Leenf1214** [comment]
你好，请问你去git上面试过了吗

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rahim"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 上午10:08
收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 
抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55)





  
taro版本：3.0.14&nbsp; taro-listview:2.0.2 设置下拉loading没有显示
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Rahim"<notifications@github.com&gt;; 发送时间: 2020年11月29日(星期天) 下午2:47 收件人: "Rahim-Chan/taro-listview"<taro-listview@noreply.github.com&gt;; 抄送: "Ⅴ"<1242600725@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [Rahim-Chan/taro-listview] taro-listview2.0版本使用以下参数下拉刷新没有生效！ (#55) @Leenf1214 H5跟小程序试过没问题呀，你的无法起作用嘛 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
有的呀，方便吧demo贴一个线上
