### ISSUE TITLE
发现了好几个bug

### ISSUE THREAD

**Issue by xu-Aurora** [Rahim-Chan/taro-listview#56]
1.footerLoading属性没有用，我是这样用的，footerLoading="loading..."
2.怎么判断下拉到底部后，没有更多数据了呢？不可能一直下拉到空数据还可以一直下拉吧？你这个例子中没有看到要怎么解决

**Comment by Rahim-Chan** [comment]
> 1.footerLoading属性没有用，我是这样用的，footerLoading="loading..."
> 2.怎么判断下拉到底部后，没有更多数据了呢？不可能一直下拉到空数据还可以一直下拉吧？你这个例子中没有看到要怎么解决

1. footerLoading没有对外暴露这个属性吧；
2. hasMore 可以控制

**Comment by xu-Aurora** [comment]
> > 1.footerLoading属性没有用，我是这样用的，footerLoading="loading..."
> > 2.怎么判断下拉到底部后，没有更多数据了呢？不可能一直下拉到空数据还可以一直下拉吧？你这个例子中没有看到要怎么解决
> 
> 1. footerLoading没有对外暴露这个属性吧；
> 2. hasMore 可以控制

1.footerLoading要怎么暴露？你不是封装好了直接通过属性使用的嘛？
2.还有就是列表展示一天数据的时候，底部还是有‘加载中’，这个又是这么解决

**Comment by Rahim-Chan** [comment]
> > > 1.footerLoading属性没有用，我是这样用的，footerLoading="loading..."
> > > 2.怎么判断下拉到底部后，没有更多数据了呢？不可能一直下拉到空数据还可以一直下拉吧？你这个例子中没有看到要怎么解决
> > 
> > 
> > 
> > 1. footerLoading没有对外暴露这个属性吧；
> > 2. hasMore 可以控制
> 
> 1.footerLoading要怎么暴露？你不是封装好了直接通过属性使用的嘛？
> 2.还有就是列表展示一天数据的时候，底部还是有‘加载中’，这个又是这么解决

wechat？聊聊？
