### ISSUE TITLE
请问是否支持2.x 以及3.x

### ISSUE THREAD

**Issue by BinZhiZhu** [Rahim-Chan/taro-listview#57]
如题，项目现在是2.x,还没迁移到3.x next，如果都支持，后续项目可以用一下这个骨架

**Comment by Rahim-Chan** [comment]
> 如题，项目现在是2.x,还没迁移到3.x next，如果都支持，后续项目可以用一下这个骨架

2.x 支持的

**Comment by BinZhiZhu** [comment]
> > 如题，项目现在是2.x,还没迁移到3.x next，如果都支持，后续项目可以用一下这个骨架
> 
> 2.x 支持的

谢谢
