### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by lifegit** [Rahim-Chan/taro-listview#58]
taro 3.1.0-beta.4 版本中，报错：Super expression must either be null or a function

复现：https://github.com/lifegit/taro-listview-bug

**Comment by lifegit** [comment]
另外请教下，release 在8月14日发布了2.0.2，为什么在10月22日发布1.4.4？

**Comment by Rahim-Chan** [comment]
> 另外请教下，release 在8月14日发布了2.0.2，为什么在10月22日发布1.4.4？ 怎么还越来越小了。

因为有部分旧版仍有使用，还要继续改bug😂

**Comment by Rahim-Chan** [comment]
> 另外请教下，release 在8月14日发布了2.0.2，为什么在10月22日发布1.4.4？ 怎么还越来越小了。

"taro-listview": "^1.4.4",这个版本对你造成对困惑我很抱歉

**Comment by lifegit** [comment]
2.0.2 可用
