### ISSUE TITLE
第一页数据未满一屏时，不能上拉请求第二页数据

### ISSUE THREAD

**Issue by P844846157** [Rahim-Chan/taro-listview#59]

**Comment by Rahim-Chan** [comment]
> _No description provided._

具体demo有吗，需要设置固定高度，且hasMore属性为true

**Comment by P844846157** [comment]
![image](https://user-images.githubusercontent.com/20579165/104531477-32370500-5649-11eb-9992-b5fa7a66c80b.png)

**Comment by Rahim-Chan** [comment]
#63
