### ISSUE TITLE
骨架屏

### ISSUE THREAD

**Issue by lifegit** [Rahim-Chan/taro-listview#6]
![image](https://user-images.githubusercontent.com/33006878/64044756-340a4080-cb9a-11e9-8796-1d5c4a1114d4.png)

是否可以给出一个完整的代码demo？并且将代码修复下错误

**Comment by Rahim-Chan** [comment]
@lifegit 
```jsx
import Taro, {useState} from '@tarojs/taro';
import {View, Button} from '@tarojs/components';
import {Skeleton} from 'components';
import './index.scss'

export default () => {
    const [isLoaded, setLoaded] = useState(false)
    return (
        <View>
            <Button onClick={() => setLoaded(!isLoaded)}>toggle</Button>
            <View className='skeleton'>
                <Skeleton isLoaded={isLoaded}>
                   {
                       Array(4).fill(1).map(i => (
                           <View className='item skeleton-bg' key={i}>
                               <View className='avatar skeleton-radius'/>
                               <View className='title skeleton-rect'>
                                   title
                               </View>
                           </View>
                       ))
                   }
                </Skeleton>
            </View>
        </View>
    )
}
```
如不清楚可直接到启动这个项目 [demo](https://github.com/Rahim-Chan/taro-listview/tree/master/src/pages)

**Comment by lifegit** [comment]
感谢！
为什么这个listview在andorid的小程序下，下拉刷新，动画会很卡呢

**Comment by Rahim-Chan** [comment]
https://github.com/Rahim-Chan/taro-listview/issues/6#issuecomment-526811408
@lifegit 
这个问题我也注意到了。原因有可能以下几种
1.安卓机H5本身的系统问题
2.图片太多，质量太大（后续会拓展懒加载模块，主要针对图片数量太多，导致内存占用过多）
3.taro生成H5的布局Html层级太深
4.下拉列表的性能优化（我已经尽力了，taro官网的下拉H5也没做啥优化呀？？搞不懂，可比较试试）

**Comment by Rahim-Chan** [comment]
> 感谢！
> 为什么这个listview在andorid的小程序下，下拉刷新，动画会很卡呢

即将修复，已经找到问题所在。

**Comment by Rahim-Chan** [comment]
> > 感谢！
> > 为什么这个listview在andorid的小程序下，下拉刷新，动画会很卡呢
> 
> 即将修复，已经找到问题所在。

安卓小程序建议用原生的吧，已经参数了wxs的实现方式，效果一样。
