### ISSUE TITLE
百度小程序下拉刷新报错Cannot read property 'eventHappen' of null

### ISSUE THREAD

**Issue by fangelyt** [Rahim-Chan/taro-listview#61]
报错提示  Cannot read property 'eventHappen' of null

(anonymous) | @ | D:\Program Files\bai…\master\events.js:1
-- | -- | --
  | (anonymous) | @ | D:\Program Files\bai…erer\event-map.js:1
  | emit | @ | events.js:203
  | onMessage | @ | init.ts:50

**Comment by Rahim-Chan** [comment]
> 报错提示 Cannot read property 'eventHappen' of null
> 
> (anonymous)	@	D:\Program Files\bai…\master\events.js:1
>  	(anonymous)	@
>  	emit	@
>  	onMessage	@

百度小程序未做兼容
