### ISSUE TITLE
支持上拉加载和下拉刷新增加活动指示器吗

### ISSUE THREAD

**Issue by Jeijie** [Rahim-Chan/taro-listview#62]
现在有个需求，上拉加载和下拉刷新都分别要增加活动指示器，但是我看到文档没有

**Comment by Rahim-Chan** [comment]
目前没有支持哦
在 2021年3月13日 +0800 PM3:17，Jeijie ***@***.***>，写道：

**Comment by Rahim-Chan** [comment]
> 现在有个需求，上拉加载和下拉刷新都分别要增加活动指示器，但是我看到文档没有
下拉可操作indicator或者单独设置tipFreedText, tipText这两个属性；
```
const { indicator = {}, tipFreedText, tipText } = this.props;
    const {
      activate = "释放刷新",
      deactivate = "下拉刷新"
    } = indicator as Indicator;
```
上拉加载等待中可自定义：renderCustomizeLoading
