### ISSUE TITLE
上拉加载更多问题

### ISSUE THREAD

**Issue by shenyuanqing** [Rahim-Chan/taro-listview#63]
上拉加载更多，第一次拉到底部触发onScrollToLower方法，再拉到底部不触发onScrollToLower方法。

**Comment by Rahim-Chan** [comment]
> 上拉加载更多，第一次拉到底部触发onScrollToLower方法，再拉到底部不触发onScrollToLower方法。

是这样的，要通过hasMore字段来控制；当`hasMore:true`当时候会回调；
`为什么这么设计呢`：
因为只有当分页列表还存在下一页当时候，回调才有意义，避免重复触发；
or你也可以直接把`hasMore`属性设置为`true`

**Comment by shenyuanqing** [comment]
@Rahim-Chan 感谢回复，hasMore一直是true没变啊

**Comment by Rahim-Chan** [comment]
> @Rahim-Chan 感谢回复，hasMore一直是true没变啊，第一次拉到底触发onScrollToLower加载了一页，再拉倒底不触发onScrollToLower方法了。
> taro:2.0.5
> taro-listview:1.1.18

抱歉，消息没有得到通知；
我突然详情，还有一个点；
- 如果你使用定义点`pullDownRefresh `点函数，是一个`async`包裹的异步函数则没有问题；
- 如果你使用用一个普通同步函数（即没有`async`包裹的），则需要回调一个`callback`函数；
``` javascript
const onScrollToLower = (cb) => {
 fetch.then(() => {
   cb() //通知异步完成了
   })
}
<ListView  onScrollToLower={onScrollToLower} />
```

**Comment by shenyuanqing** [comment]
@Rahim-Chan，对的，之前是同步函数没有写回调，改成异步后可以连续翻页了，但发现每次翻页的时候onScrollToLower方法一下子调了好几次，什么情况？

```
  onScrollToLower =  async (fn) => {
    console.warn('onScrollToLower')
    this.setState({
      list: this.state.list.concat([{}, {}, {}, {}, {}]),
      hasMore: true,
    });
    fn();
  };

  render() {
    return (
      <View className='index'>
        <ListView
          hasMore={this.state.hasMore}
          onScrollToLower={fn=>this.onScrollToLower(fn)}
          style={{height: '100vh'}}
        >
          {this.state.list.map((item, index) => {
            return (
              <View key={index} className='item_container'>
                <Text>aaa{index+1}</Text>
              </View>
            )
          })}
        </ListView>
      </View>
    )
  }
```

**Comment by Rahim-Chan** [comment]
> @Rahim-Chan，对的，之前是同步函数没有写回调，改成异步后可以连续翻页了，但发现每次翻页的时候onScrollToLower方法一下子调了好几次，什么情况？
> 
> ```
>   onScrollToLower =  async (fn) => {
>     console.warn('onScrollToLower')
>     this.setState({
>       list: this.state.list.concat([{}, {}, {}, {}, {}]),
>       hasMore: true,
>     });
>     fn();
>   };
> 
>   render() {
>     return (
>       <View className='index'>
>         <ListView
>           hasMore={this.state.hasMore}
>           onScrollToLower={fn=>this.onScrollToLower(fn)}
>           style={{height: '100vh'}}
>         >
>           {this.state.list.map((item, index) => {
>             return (
>               <View key={index} className='item_container'>
>                 <Text>aaa{index+1}</Text>
>               </View>
>             )
>           })}
>         </ListView>
>       </View>
>     )
>   }
> ```

原因可能如下：
- 如果是在微信小程序环境下的效果（亲身体验过，小程序的onScrollToLower有点问题、本身组件内部已经加了节流）；
方法：
- 延迟callback函数的回调；（因为onScrollToLower的触发机制也是依赖原生组件的，这一点可能与渲染高度有关）
- 或者你可以包裹上一个节流函数（组件内部自身其实已经加了节流了）

**Comment by shenyuanqing** [comment]
@Rahim-Chan 加个延时解决问题，感谢！
