### ISSUE TITLE
关于小程序模式下拉在安卓机上卡顿

### ISSUE THREAD

**Issue by Rahim-Chan** [Rahim-Chan/taro-listview#8]
这个问题我也注意到了。原因有可能以下几种
1.安卓机H5本身的系统问题
2.图片太多，质量太大（后续会拓展懒加载模块，主要针对图片数量太多，导致内存占用过多）
3.taro生成H5的布局Html层级太深
4.下拉列表的性能优化（我已经尽力了，taro官网的下拉H5也没做啥优化呀？？搞不懂，可比较试试）

**Comment by Rahim-Chan** [comment]
安卓机下拉卡顿即将修复

**Comment by Rahim-Chan** [comment]
安卓机型小程序下拉卡顿无解，
![image](https://user-images.githubusercontent.com/18487314/70609559-f5762e80-1c3c-11ea-86c7-1e12db56cf94.png)
已经参照官方给出的WXS实现方案去尝试，效果已经糟糕。
就连官网的DEMO跑起来也很卡。

**Comment by Norbert-Nayman** [comment]
> 安卓机型小程序下拉卡顿无解，
> ![image](https://user-images.githubusercontent.com/18487314/70609559-f5762e80-1c3c-11ea-86c7-1e12db56cf94.png)
> 已经参照官方给出的WXS实现方案去尝试，效果已经糟糕。
> 就连官网的DEMO跑起来也很卡。

安卓机型可不可以定制成 安卓版chrome 或者安卓版知乎 那种下拉小圆圈 不动view的那种效果

**Comment by Rahim-Chan** [comment]
> > 安卓机型小程序下拉卡顿无解，
> > ![image](https://user-images.githubusercontent.com/18487314/70609559-f5762e80-1c3c-11ea-86c7-1e12db56cf94.png)
> > 已经参照官方给出的WXS实现方案去尝试，效果已经糟糕。
> > 就连官网的DEMO跑起来也很卡。
> 
> 安卓机型可不可以定制成 安卓版chrome 或者安卓版知乎 那种下拉小圆圈 不动view的那种效果

是想尽量的模仿安卓的material吗？我觉得不是很必要

**Comment by Rahim-Chan** [comment]
> > 安卓机型小程序下拉卡顿无解，
> > ![image](https://user-images.githubusercontent.com/18487314/70609559-f5762e80-1c3c-11ea-86c7-1e12db56cf94.png)
> > 已经参照官方给出的WXS实现方案去尝试，效果已经糟糕。
> > 就连官网的DEMO跑起来也很卡。
> 
> 安卓机型可不可以定制成 安卓版chrome 或者安卓版知乎 那种下拉小圆圈 不动view的那种效果

是想尽量的模仿安卓的material吗？我觉得不是很必要
